/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// PositionResponse PositionResponse is the response you get when interacting with the Position API
type PositionResponse struct {
	// The ID of the Position
	Id int64 `json:"id"`
	// The ID of the Tracker the position belongs to
	TrackerId int64 `json:"trackerId"`
	// The UNIX timestamp of the position. If omitted, server timestamp will be used.
	Timestamp int64 `json:"timestamp"`
	// Latitude of the position
	Lat float32 `json:"lat"`
	// Longitude of the position
	Lng float32 `json:"lng"`
	// Altitude of the position
	Alt float32 `json:"alt"`
	// Heading in degrees
	Heading float32 `json:"heading"`
	// Speed in knots
	Speed float32 `json:"speed"`
	// Normalized precision between 0..1
	Precision float32 `json:"precision"`
	// Arbritary payload connected to the position. Max size of 10 KB.
	Payload string `json:"payload"`
}
