/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// SubscriptionConfidenceType the model 'SubscriptionConfidenceType'
type SubscriptionConfidenceType string

// List of SubscriptionConfidenceType
const (
	LOW SubscriptionConfidenceType = "low"
	MEDIUM SubscriptionConfidenceType = "medium"
	HIGH SubscriptionConfidenceType = "high"
)
