/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// ShapeCollectionResponse ShapeCollectionResponse is the response you get when interacting with the ShapeCollection API
type ShapeCollectionResponse struct {
	// The ID of the ShapeCollection
	Id int64 `json:"id"`
	// The Team ID of the ShapeCollection
	TeamId int64 `json:"teamId"`
	// The name of the ShapeCollection
	Name string `json:"name"`
	// The description of the ShapeCollection
	Description string `json:"description"`
}
