/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// GeoJsonFeature GeoJSON Feature
type GeoJsonFeature struct {
	// The type of the feature. This value can only be \"Feature\"
	Type string `json:"type"`
	Geometry Geometry `json:"geometry"`
	// Feature properties
	Properties map[string]map[string]interface{} `json:"properties"`
}
