/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// EditTeamRequest EditTeamRequest is a object to be used when updating a Team
type EditTeamRequest struct {
	// The updated name of the Team
	Name string `json:"name"`
	// The updated description of the Team
	Description string `json:"description"`
}
