/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// EditCollectionRequest A EditCollectionRequest is used when editing a Collection
type EditCollectionRequest struct {
	// The updated name of the Collection
	Name string `json:"name"`
	// The updated Collection description
	Description string `json:"description"`
	// The Team ID of the Collection
	TeamId int64 `json:"teamId"`
}
