/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// ErrorDetail struct for ErrorDetail
type ErrorDetail struct {
	// String representation of the field which has an error
	Field string `json:"field"`
	// Reason to what is wrong with the field given in `field`
	Reason string `json:"reason"`
}
