/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// EditSubscriptionRequest struct for EditSubscriptionRequest
type EditSubscriptionRequest struct {
	// The Team ID of the Subscription
	TeamId int64 `json:"teamId"`
	// The updated name of the Subscription
	Name string `json:"name"`
	// The updated description of the Subscription
	Description string `json:"description"`
	// Updated boolean showing whether the subscription is active
	Active bool `json:"active"`
	Output SubscriptionOutput `json:"output"`
	TriggerCriteria SubscriptionResponseTriggerCriteria `json:"triggerCriteria"`
	// The ID of the ShapeCollection containing shapes to subscribe to
	ShapeCollectionId int64 `json:"shapeCollectionId"`
	Trackable SubscriptionResponseTrackable `json:"trackable"`
}
