/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// SubscriptionResponseTrackable Details of which entities the subscription tracks
type SubscriptionResponseTrackable struct {
	// The ID of the trackable entity
	Id float32 `json:"id"`
	Type SubscriptionTrackerType `json:"type"`
}
