/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// NewTrackerRequest struct for NewTrackerRequest
type NewTrackerRequest struct {
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
}
