/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// PointAllOf struct for PointAllOf
type PointAllOf struct {
	// The type of geometry
	Type string `json:"type"`
	// Point in 2D space
	Coordinates []float32 `json:"coordinates"`
}
