/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// ShapeResponse ShapeResponse is the response you get when interacting with the ShapeCollection API
type ShapeResponse struct {
	// The ID of the Shape
	Id int64 `json:"id"`
	// The ShapeCollection ID of the Shape
	ShapeCollectionId int64 `json:"shapeCollectionId"`
	// The name of the Shape, derived from the GeoJSON feature
	Name string `json:"name"`
	// The properties connected to the Shape, derived from GeoJSON feature
	Properties map[string]map[string]interface{} `json:"properties"`
}
