/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// SubscriptionResponseTriggerCriteria The trigger criterias for a Subscription
type SubscriptionResponseTriggerCriteria struct {
	// The different types of triggers that should trigger the Subscription
	TriggerTypes []SubscriptionTriggerType `json:"triggerTypes"`
	// The confidence level of which the Subscription should trigger. The value is provided with the position and is a normalized value from `0..1`  * `low`: Low means a confidence of `[0 .. 0.4]` * `medium`: Medium means a confidence of `(0.4 .. 0.8]` * `high`: High means a confidence of `(0.8 .. 1]` 
	Confidence []SubscriptionConfidenceType `json:"confidence"`
}
