/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// NewShapeCollectionRequest struct for NewShapeCollectionRequest
type NewShapeCollectionRequest struct {
	// The Team ID of the ShapeCollection
	TeamId int64 `json:"teamId"`
	// The name of the ShapeCollection
	Name string `json:"name,omitempty"`
	// The description of the ShapeCollection
	Description string `json:"description,omitempty"`
}
