/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// NewPositionRequest struct for NewPositionRequest
type NewPositionRequest struct {
	// The UNIX timestamp of the position. If omitted, server timestamp will be used.
	Timestamp int64 `json:"timestamp,omitempty"`
	// Latitude of the position
	Lat float32 `json:"lat"`
	// Longitude of the position
	Lng float32 `json:"lng"`
	// Altitude of the position
	Alt float32 `json:"alt,omitempty"`
	// Heading in degrees
	Heading float32 `json:"heading,omitempty"`
	// Speed in knots
	Speed float32 `json:"speed,omitempty"`
	// Normalized precision between 0..1
	Precision float32 `json:"precision,omitempty"`
	// Arbritary payload connected to the position. Max size of 10 KB.
	Payload string `json:"payload,omitempty"`
}
