/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// ProfileResponse ProfileResponse is the response you get when interacting with the Profile API
type ProfileResponse struct {
	// The ID of the Profile
	Id int64 `json:"id"`
	// Name of the user connected to the Profile
	Name string `json:"name"`
	// The email of the user connected to the Profile
	Email string `json:"email"`
	// Whether the email has been verified for the user
	EmailVerified bool `json:"emailVerified"`
	// The phone number of the user connected to the Profile
	Phone string `json:"phone"`
	// Whether the phone number has been verified for the user
	PhoneNumberVerified bool `json:"phoneNumberVerified"`
	// The date of the Profile creation
	Created string `json:"created"`
}
