/*
 * Places API
 *
 * The Places API provides access to the different features of the Lab5e Places server, including capabilities such as pub/sub, geofencing and storage of tracking data. 
 *
 * API version: v0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goplaces
// TrackerResponse TrackerResponse is the response you get when interacting with the Tracker API
type TrackerResponse struct {
	// The ID of the Tracker
	Id int64 `json:"id"`
	// The Collection ID of the Tracker
	CollectionId int64 `json:"collectionId"`
	// The name of the Tracker
	Name string `json:"name"`
	// The description of the Tracker
	Description string `json:"description"`
}
